### ISSUE TITLE
Timed out waiting for container port to open (localhost ports: [32777, 2222] should be listening)

### ISSUE THREAD

**Issue by juanux** [panubo/docker-sshd#61]
With this config : 
```
   sftp:
    image: panubo/sshd:1.2.0
    hostname: sftp
    ports:
      - "2222:22"
    environment:
      SSH_USERS: tradegateag:1000:1000
    volumes:
      - "./ssh/id_rsa.pub:/etc/authorized_keys/tradegateag:ro"


```

I'm hving this exception.

```
[info]   java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [32777, 2222] should be listening)
[info]   at org.rnorth.ducttape.timeouts.Timeouts.callFuture(Timeouts.java:68)
[info]   at org.rnorth.ducttape.timeouts.Timeouts.doWithTimeout(Timeouts.java:60)
[info]   at org.testcontainers.containers.wait.strategy.WaitAllStrategy.waitUntilReady(WaitAllStrategy.java:53)
[info]   at org.testcontainers.containers.DockerComposeContainer.waitUntilServiceStarted(DockerComposeContainer.java:254)
[info]   at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
[info]   at org.testcontainers.containers.DockerComposeContainer.waitUntilServiceStarted(DockerComposeContainer.java:234)
[info]   at org.testcontainers.containers.DockerComposeContainer.start(DockerComposeContainer.java:173)
[info]   at com.dimafeng.testcontainers.DockerComposeContainer.start(DockerComposeContainer.scala:166)
[info]   at com.dimafeng.testcontainers.ForAllTestContainer.run(ForAllTestContainer.scala:17)
[info]   at com.dimafeng.testcontainers.ForAllTestContainer.run$(ForAllTestContainer.scala:13)
[info]   ...
[info]   Cause: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [32777, 2222] should be listening)
[info]   at org.testcontainers.containers.wait.strategy.HostPortWaitStrategy.waitUntilReady(HostPortWaitStrategy.java:49)
[info]   at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
[info]   at org.testcontainers.containers.wait.strategy.WaitAllStrategy.waitUntilNestedStrategiesAreReady(WaitAllStrategy.java:61)
[info]   at org.testcontainers.containers.wait.strategy.WaitAllStrategy.lambda$waitUntilReady$0(WaitAllStrategy.java:54)
[info]   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[info]   at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by macropin** [comment]
I'm sorry, we're not able to provide support for this in GitHub. This very much looks like a configuration issue.
